### ISSUE TITLE
Orders API Review

### ISSUE THREAD

**Issue by nickcoleman** [CruxConnect/crux-docs#107]
Review existing the Order API docs. 

- [x] Get Orders POST '/orders/'
- [x] Get Orders Export POST '/orders/export/'
- [x] Get Order Detail  `/orders/${uuid}/`
- [x] Get Order Fees - Retailer POST '/orders/fees/'
- [x] Create Order - Retailer
- [x] Cancel Order
- [x] Cancel Order Item - Retailer

Add following docs
- [x] Add Orders Tracking Post `/orders/tracking/${orderUUID}
- [x] Allocate Order Put `/orders/allocation/${orderUUID}/`

Incorporate already identified issues.  To include:
- [x] #63 Add endpoint to Orders Export
- [x] #85 Order allocation response change
- [x] #106 Order status conjunction
